name: Submission Handling

on:
  pull_request:
    branches:
      - submissions 

jobs:
  handle_submission:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history to preserve user folder names

      - name: Get PR info
        id: pr_info
        run: |
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "pr_head_ref=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          echo "pr_user=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV

      - name: Create submission folder
        run: mkdir -p submissions/${{ env.pr_user }}

      - name: Move submission files
        run: |
          mv ${{ github.workspace }}/submission/* submissions/${{ env.pr_user }}/

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add submissions/${{ env.pr_user }}
          git commit -m "Submission from ${{ env.pr_user }} (PR #${{ env.pr_number }})"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: submissions